"""bake_offline.py - make ui/index.html work from file:// (offline / USB stick).

BIPES's xhrGET() has two modes: on http(s) it fetches toolbox XML and
devinfo.json; on file:// it instead reads pre-baked assets:
  - toolbox  ->  a hidden DOM element  #OFFLINE_toolbox_<name>_xml
  - devinfo  ->  a JS global           OFFLINE_devinfo_devinfo_json
  - pylibs   ->  a JS global           OFFLINE_pylibs_<name>_py
Stock BIPES ships those baked assets only in index_offline.html (which has
none of our classroom customisations). This script bakes OUR live assets into
OUR index.html, so the same file works served AND from a local folder.

Run from the repo root:   python bake_offline.py
Idempotent: re-run any time the toolbox changes, it replaces the old block.
"""

import json
import os
import re

UI = "ui"
INDEX = os.path.join(UI, "index.html")
DEVINFO = os.path.join(UI, "devinfo", "devinfo.json")
TOOLBOXES = ["esp32.xml", "default.xml"]      # esp32 = ours; default = fallback
# Files tab "Library files" picker (ui/core/utils.js, files.PYLIB_FILES) -
# keep this list in sync with that one.
PYLIBS = ["gyro.py", "vl53l0x_nb.py", "ssd1306.py", "invaders.py", "snake.py", "defender.py", "mmcal.py"]

START = "<!-- BAKED-OFFLINE-ASSETS-START (generated by bake_offline.py) -->"
END = "<!-- BAKED-OFFLINE-ASSETS-END -->"


def js_template_literal_escape(text):
    """Make `text` safe to embed verbatim inside a `...` JS template literal.

    Checking for a bare backtick or ${ (the original approach here) is not
    enough: a template literal ALSO interprets backslash escapes exactly
    like an ordinary JS string. Real Python source routinely contains
    sequences like b'\\x00' - to JS that four-character \\x00 is a single
    NUL-byte escape, silently shrinking the baked copy by three characters
    per occurrence with no error raised anywhere. Escaping the backslash
    itself first (so \\x00 becomes the four literal characters \\, x, 0, 0
    again once JS un-escapes the leading \\\\) fixes that at the source
    instead of hoping the content never contains one of these.
    Order matters: escape backslashes FIRST, so the backslashes this
    function adds for ` and $ are not themselves re-escaped.
    """
    return text.replace("\\", "\\\\").replace("`", "\\`").replace("$", "\\$")


def main():
    if not os.path.exists(INDEX):
        raise SystemExit("run this from the repo root (ui/index.html not found)")

    parts = [START]

    # 1. toolbox XML -> hidden <document> elements, id per BIPES's naming:
    #    "toolbox/esp32.xml" -> non-alphanumerics to _ -> OFFLINE_toolbox_esp32_xml
    for tb in TOOLBOXES:
        path = os.path.join(UI, "toolbox", tb)
        if not os.path.exists(path):
            print("  skip (missing):", path)
            continue
        xml = open(path, encoding="utf-8").read()
        # BIPES wraps the categories in <document>; strip the file's own wrapper
        xml = re.sub(r"</?document>", "", xml).strip()
        key = ("toolbox/" + tb).replace("/", "_").replace(".", "_")
        parts.append("<document style='display: none' id='OFFLINE_%s'>" % key)
        parts.append(xml)
        parts.append("</document>")
        print("  baked toolbox:", tb, "->", "OFFLINE_" + key)

    # 2. devinfo.json -> JS global as a template literal (BIPES JSON.parse's it)
    #    The whole `...`; assignment is ONE parts element, not three joined by
    #    "\n".join() below - that join would otherwise add its own newline
    #    before and after raw, leaving the baked copy 2 bytes longer than the
    #    real file (harmless for JSON.parse/Python, but needlessly inexact).
    if os.path.exists(DEVINFO):
        raw = open(DEVINFO, encoding="utf-8").read()
        json.loads(raw)                      # fail loudly if it is not valid JSON
        parts.append("<script>")
        parts.append("OFFLINE_devinfo_devinfo_json = `%s`;" % js_template_literal_escape(raw))
        parts.append("</script>")
        print("  baked devinfo.json")

    # 3. pylibs/*.py -> JS globals as template literals, same mechanism as
    #    devinfo.json above (plain text, not JSON, so no json.loads check -
    #    xhrGET's offline branch hands the string back as-is for these).
    for name in PYLIBS:
        path = os.path.join(UI, "pylibs", name)
        if not os.path.exists(path):
            print("  skip (missing):", path)
            continue
        raw = open(path, encoding="utf-8").read()
        key = ("pylibs/" + name).replace("/", "_").replace(".", "_")
        parts.append("<script>")
        parts.append("OFFLINE_%s = `%s`;" % (key, js_template_literal_escape(raw)))
        parts.append("</script>")
        print("  baked pylib:", name, "->", "OFFLINE_" + key)

    parts.append(END)
    block = "\n".join(parts)

    html = open(INDEX, encoding="utf-8").read()
    if START in html:                        # replace an earlier bake
        # A lambda, not `block` directly: re.sub() treats a string repl as
        # its own mini-template and interprets backslash sequences in it
        # (\1, \g<...>, ...). Baked pylib source containing a byte literal
        # like b'\x00' hits that directly - "bad escape \x". A callable
        # return value is inserted literally, with no such interpretation.
        html = re.sub(re.escape(START) + r"[\s\S]*?" + re.escape(END), lambda _m: block, html)
        print("  replaced previous baked block")
    else:                                    # first bake: insert before </html>
        if "</html>" not in html:
            raise SystemExit("no </html> in index.html - cannot insert")
        html = html.replace("</html>", block + "\n</html>", 1)
        print("  inserted baked block before </html>")

    open(INDEX, "w", encoding="utf-8", newline="\n").write(html)
    print("done -> ui/index.html now works from file:// as well as served")


if __name__ == "__main__":
    main()
