"""bake_offline.py - make ui/index.html work from file:// (offline / USB stick).

BIPES's xhrGET() has two modes: on http(s) it fetches toolbox XML and
devinfo.json; on file:// it instead reads pre-baked assets:
  - toolbox  ->  a hidden DOM element  #OFFLINE_toolbox_<name>_xml
  - devinfo  ->  a JS global           OFFLINE_devinfo_devinfo_json
Stock BIPES ships those baked assets only in index_offline.html (which has
none of our classroom customisations). This script bakes OUR live assets into
OUR index.html, so the same file works served AND from a local folder.

Run from the repo root:   python bake_offline.py
Idempotent: re-run any time the toolbox changes, it replaces the old block.
"""

import json
import os
import re

UI = "ui"
INDEX = os.path.join(UI, "index.html")
DEVINFO = os.path.join(UI, "devinfo", "devinfo.json")
TOOLBOXES = ["esp32.xml", "default.xml"]      # esp32 = ours; default = fallback

START = "<!-- BAKED-OFFLINE-ASSETS-START (generated by bake_offline.py) -->"
END = "<!-- BAKED-OFFLINE-ASSETS-END -->"


def main():
    if not os.path.exists(INDEX):
        raise SystemExit("run this from the repo root (ui/index.html not found)")

    parts = [START]

    # 1. toolbox XML -> hidden <document> elements, id per BIPES's naming:
    #    "toolbox/esp32.xml" -> non-alphanumerics to _ -> OFFLINE_toolbox_esp32_xml
    for tb in TOOLBOXES:
        path = os.path.join(UI, "toolbox", tb)
        if not os.path.exists(path):
            print("  skip (missing):", path)
            continue
        xml = open(path, encoding="utf-8").read()
        # BIPES wraps the categories in <document>; strip the file's own wrapper
        xml = re.sub(r"</?document>", "", xml).strip()
        key = ("toolbox/" + tb).replace("/", "_").replace(".", "_")
        parts.append("<document style='display: none' id='OFFLINE_%s'>" % key)
        parts.append(xml)
        parts.append("</document>")
        print("  baked toolbox:", tb, "->", "OFFLINE_" + key)

    # 2. devinfo.json -> JS global as a template literal (BIPES JSON.parse's it)
    if os.path.exists(DEVINFO):
        raw = open(DEVINFO, encoding="utf-8").read()
        json.loads(raw)                      # fail loudly if it is not valid JSON
        if "`" in raw or "${" in raw:
            raise SystemExit("devinfo.json contains ` or ${ - would break the template literal")
        parts.append("<script>")
        parts.append("OFFLINE_devinfo_devinfo_json = `")
        parts.append(raw)
        parts.append("`;")
        parts.append("</script>")
        print("  baked devinfo.json")

    parts.append(END)
    block = "\n".join(parts)

    html = open(INDEX, encoding="utf-8").read()
    if START in html:                        # replace an earlier bake
        html = re.sub(re.escape(START) + r"[\s\S]*?" + re.escape(END), block, html)
        print("  replaced previous baked block")
    else:                                    # first bake: insert before </html>
        if "</html>" not in html:
            raise SystemExit("no </html> in index.html - cannot insert")
        html = html.replace("</html>", block + "\n</html>", 1)
        print("  inserted baked block before </html>")

    open(INDEX, "w", encoding="utf-8", newline="\n").write(html)
    print("done -> ui/index.html now works from file:// as well as served")


if __name__ == "__main__":
    main()
